version: "3.8"

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "8081:80" # Change this line to use port 8081 on the host
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front_end

  front_end:
    build: ./front_end
    ports:
      - "8080:8080"
    depends_on:
      - manager
      - data_node1
      - data_node2
    environment:
      - MANAGER_HOST=manager:8090
      - DATA_NODE_HOSTS=data_node1:9001,data_node2:9002

  manager:
    build: ./manager
    platform: linux/amd64
    ports:
      - "8090:8090"
    depends_on:
      - metadata_storage
    environment:
      - METADATA_STORAGE_HOST=metadata_storage
      - METADATA_STORAGE_PORT=5432
      - POSTGRES_DB=blobstore
      - POSTGRES_USER=blobstore_user
      - POSTGRES_PASSWORD=blobstore_password
    volumes:
      - manager_logs:/logs

  data_node1:
    build: ./data_node
    ports:
      - "9001:9001"
    volumes:
      - data_node1_storage:/data

  data_node2:
    build: ./data_node
    ports:
      - "9002:9002"
    volumes:
      - data_node2_storage:/data

  metadata_storage:
    image: postgres:latest
    environment:
      POSTGRES_DB: blobstore
      POSTGRES_USER: blobstore_user
      POSTGRES_PASSWORD: blobstore_password
    volumes:
      - metadata_storage_data:/var/lib/postgresql/data
      - ./metadata_storage/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  data_node1_storage:
  data_node2_storage:
  metadata_storage_data:
  manager_logs:
