global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'front_end'
    static_configs:
      - targets: ['front_end:8080']

  - job_name: 'manager'
    static_configs:
      - targets: ['manager:8090']

  - job_name: 'data_node1'
    static_configs:
      - targets: ['data_node1:9001']

  - job_name: 'data_node2'
    static_configs:
      - targets: ['data_node2:9002']
